name: build

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.png"
  pull_request:

env:
  IMAGE_NAME: atmoz/sftp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # for proper signature verification
          submodules: true # for shunit2

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore: tests/shunit2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: reddy1991
          password: ${{ secrets.SFTP-TOKEN }}

      - name: Build and publish debian image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            reddy1991/sftp:debian
            reddy1991/sftp:latest
      - name: Build and publish alpine images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-alpine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            reddy1991/sftp:alpine
